# Generated by Django 5.0.6 on 2024-07-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=200)),
                ('question1', models.CharField(max_length=5000)),
                ('question2', models.CharField(max_length=5000)),
                ('question3', models.CharField(max_length=5000)),
                ('question4', models.CharField(max_length=5000)),
                ('question5', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='getStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=5000)),
                ('answer2', models.CharField(max_length=5000)),
                ('answer3', models.CharField(max_length=5000)),
                ('answer4', models.CharField(max_length=5000)),
                ('answer5', models.CharField(max_length=5000)),
                ('score', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'profile__user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='takeanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=5000)),
                ('answer2', models.CharField(max_length=5000)),
                ('answer3', models.CharField(max_length=5000)),
                ('answer4', models.CharField(max_length=5000)),
                ('answer5', models.CharField(max_length=5000)),
                ('score', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'profile__user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=200)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('tutor', models.ForeignKey(limit_choices_to={'profile__user_type': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
