# Generated by Django 5.0.6 on 2024-07-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_takeanswers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeanswers',
            name='question',
        ),
    ]
