# Generated by Django 5.0.6 on 2024-07-07 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_takeanswers_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeanswers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.testquestions'),
            preserve_default=False,
        ),
    ]
