# Generated by Django 5.1.4 on 2025-04-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestions',
            name='exam_time',
            field=models.IntegerField(default=5, help_text='Exam time in minutes'),
        ),
    ]
