# Generated by Django 5.1.4 on 2025-04-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_objectiveexam_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
    ]
